### PR TITLE
Update supernova classifier module version from `v0.6` to `v0.7`

### PR DESCRIPTION
**Pull request by hernandezc1**
Since the start of the original ELAsTiCC challenge, the supernova classifier module has undergone a few changes. These changes were introduced without declaring an updated version (currently `v0.6`). For the ELAsTiCC2 challenge, we are formalizing the module's version as `v0.7`. 

For the ELAsTiCC2 challenge, we have:
- updated `main.py` and `bq_elasticc_SuperNNova_schema.json` to include additional fields in the BigQuery table
- updated `main.py` to accommodate ELAsTiCC's [new schema](https://github.com/LSSTDESC/elasticc/tree/main/alert_schema) (`v0.9.1`)
- generalized variable and function names

Future updates to the classifier module will result in updated version declarations.

Should this PR should be merged after merging PR #20?

### CODE REVIEW

**Comment by troyraen** [comment]
I suppose we should add this "brokerVersion" to the BigQuery table as well since otherwise we'll have no permanent record of which alerts were processed using which version. Let's stick with the field name "brokerVersion" to match the outgoing Avro schema, but clarify in the field description that this is the version of our classifier module.

> Should this PR should be merged after merging PR https://github.com/mwvgroup/pittgoogle-user/pull/20?

No, this PR should go through ASAP to track the changes that have already been made.

**Comment by hernandezc1** [comment]
I added the `brokerVersion` to the BigQuery table and tested it. You can review the BigQuery table [here](https://console.cloud.google.com/bigquery?project=elasticc-challenge&ws=!1m5!1m4!4m3!1selasticc-challenge!2selasticc_alerts_moduleversion!3sSuperNNova)

**Review by troyraen — APPROVED** [review]
I strongly recommend defining variables only once. Here you're defining the same `brokerVersion` in two different places. This makes it easy to introduce errors in the future because it's easy to forget (or for others to not even realize) that the version has to be updated in two different places. Our handling of this variable will improve a bit after #20 but I still recommend changing it here to avoid the problem altogether.

Otherwise, LGTM.

**Comment by hernandezc1** [comment]
I've updated `main.py` so that `brokerVersion` is only defined once

> I strongly recommend defining variables only once. Here you're defining the same `brokerVersion` in two different places. This makes it easy to introduce errors in the future because it's easy to forget (or for others to not even realize) that the version has to be updated in two different places. Our handling of this variable will improve a bit after #20 but I still recommend changing it here to avoid the problem altogether.

**Pull request merged**
